### ISSUE TITLE
Search with '/' segfaults under Linux

### ISSUE THREAD

**Issue by 316k** [gabc/much#2]
Anytime I try to search in the text with '/', the software just segfaults.

Using Fedora 22 core-4.1-amd64:core-4.1-noarch, with a Sony Vaio laptop (4Go RAM)
Graphical card : 01:00.0 VGA compatible controller: NVIDIA Corporation GT218M [GeForce 310M](rev a2)

**Comment by gabc** [comment]
Fixed.
